runtime: nodejs8
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /
  static_files: dist/hainayanda-blog/index.html
  upload: dist/hainayanda-blog/index.html
- url: /
  static_dir: dist/hainayanda-blog